apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  ports:
    - port: 13133
      name: healthcheck
      protocol: TCP
      targetPort: 13133
    - port: 4317
      name: grpc
      protocol: TCP
      targetPort: 4317
  selector:
    name: otel-collector
  type: ClusterIP