schemaVersion: 2.2.0
metadata:
  name: agentic-quarkus-app
components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel9:3.25.0
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
        - name: KUBEDOCK_ENABLED
          value: 'true'
        - name: DOCKER_HOST
          value: 'tcp://127.0.0.1:2475'
        - name: TESTCONTAINERS_RYUK_DISABLED
          value: 'true'
        - name: TESTCONTAINERS_CHECKS_DISABLE
          value: 'true'
        - name: VSCODE_JAVA_EXEC
          value: '/usr/lib/jvm/java-21-openjdk/bin/java'
        - name: JAVA_HOME
          value: '/usr/lib/jvm/java-21-openjdk/'
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: none
          name: test
          protocol: http
          targetPort: 8081
        - exposure: public
          name: parasol-webui
          protocol: https
          targetPort: 8080
        - exposure: public
          name: quarkus-devui
          path: /q/dev-ui
          protocol: https
          targetPort: 8080
        - exposure: public
          name: mailpit
          path: /q/mailpit
          protocol: https
          targetPort: 8080
      memoryRequest: 5Mi
      memoryLimit: 6G
      cpuRequest: 1000m
commands:
  - id: set-java-bin
    exec:
      component: tools
      commandLine: "ln -f -s /usr/lib/jvm/java-21-openjdk/bin /home/user/.java/current"
      workingDir: "/home/user"
events:
  postStart: 
    - set-java-bin
      cpuLimit: 4000m
